Gura - recreated pull request
toleksyn/ifa-120.ta pull request #109
Opened 2021-04-15 06:28 UTC by Gura-Andriy

2021-04-15 15:37 UTC, SofiiaPro commented on src/test/java/com/softserveinc/ita/rozetka_test/OrderTest.java
> +        Assert.assertTrue(openOrderPage.getPageTitle().equals("Оформлення замовлення"), "The page title shouldn't match the condition");
divide methods.
.getPageTitile()
.equals()

2021-04-16 06:34 UTC, toleksyn requested changes

2021-04-16 06:34 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/OrderTest.java
> +        Assert.assertTrue(!openOrderPage.getPageTitle().isEmpty(), "The title shouldn't found on page");
shouldn't be empty

2021-04-16 06:34 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/OrderTest.java
> +        Assert.assertTrue(openOrderPage.getPageTitle().equals("Оформлення замовлення"), "The page title shouldn't match the condition");
openOrderPage.getPageTitle() to var

2021-04-16 06:34 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/OrderTest.java
> +        Assert.assertTrue(openOrderPage.getPageTitle().equals("Оформлення замовлення"), "The page title shouldn't match the condition");
should be

2021-04-19 05:31 UTC, toleksyn requested changes

2021-04-19 05:31 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/OrderPage.java
>          return new BasketPage();
resolve conflicts

2021-04-19 05:48 UTC, Gura-Andriy commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/OrderPage.java
>          return new BasketPage();
I haven't conflicts O_O

2021-04-20 05:24 UTC, toleksyn requested changes

2021-04-20 05:24 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/BasketPage.java
> +    public BasketPage deleteGoods(int indexOfGoods) {
you're deleting single product, rename
no 'of' in names

2021-04-20 05:24 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/BasketPage.java
> +        $$x("//app-buy-button[@class='toOrder']").get(indexOfGoods).click();
inefficient, re-do

2021-04-20 05:24 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/BasketPage.java
> +    public BasketPage deleteGoods(int indexOfGoods) {
not good, product

2021-04-20 05:24 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/BasketPage.java
> +        return new BasketPage();
return this;

2021-04-21 05:25 UTC, toleksyn requested changes

2021-04-21 05:25 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/BasketPage.java
> +    public String getDeletedFromBasketProductLink(int productIndex) {
rename

2021-04-21 05:25 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/BasketPage.java
> +    public String getProductInBasketLink(int productIndex) {
rename

2021-04-21 05:25 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/BasketTest.java
> +
remove

2021-04-21 05:25 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/BasketTest.java
> +    public void testRestoreDeletedOrder() {
rename

2021-04-21 05:25 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/OrderTest.java
> +    }
re-design case

2021-04-21 06:23 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/BasketPage.java
> +    public String getDeletedFromBasketProductLink(int productIndex) {
getRecentlyViewedProductsSection().getProduct(1).getLink()

2021-04-22 06:46 UTC, closed without merging