sbendus - create first rozetka test
toleksyn/ifa-120.ta pull request #115
Opened 2021-04-15 12:57 UTC by SofiiaPro

2021-04-15 15:09 UTC, VladimirPetrat commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        Assert.assertTrue(catalogCategoryItem.getPageTitle().contains("Комп'ютери"),
Add string to local variable

2021-04-15 15:11 UTC, VladimirPetrat commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        Assert.assertTrue(catalogCategoryItem.getPageTitle().contains("Комп'ютери"),
Problem with mapping

2021-04-15 15:11 UTC, VladimirPetrat commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        chosenProduct.openCategoryPageByName("ноутбуки");
Use pageCategoryName variable

2021-04-15 19:12 UTC, SofiiaPro commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/WishListPage.java
> +
//STILL IN PROGRESS.
Applies to the SECOND test case.

2021-04-15 19:12 UTC, SofiiaPro commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/LeftSidebar.java
> +    }
//STILL IN PROGRESS.
Applies to the SECOND test case.

2021-04-15 19:15 UTC, SofiiaPro commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CategoryPage.java
> +    }
misunderstood with page title (header in the page) and page URL title.

divide these into:
page title - string title on the page
URL title - title in URL

2021-04-15 19:16 UTC, SofiiaPro commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductPage.java
> +    }
//STILL IN PROGRESS.
Applies to the SECOND test case.

2021-04-16 05:25 UTC, toleksyn requested changes

2021-04-16 05:25 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CategoryPage.java
> +    public String getPageUrlTitle() {
that's not url

2021-04-16 05:25 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductPage.java
> +    public Integer getProductOldPrice() {
old means pre-discount?

2021-04-16 05:25 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductPage.java
> +    public Integer getProductWithSale() {
rename

2021-04-16 05:25 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/WishListPage.java
> +    public String getProductTitleFromWishProductList(String message) {
rename all

2021-04-16 05:25 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +    public void testSelectProductByCatalog() {
rename

2021-04-16 05:25 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        String pageTitle = "Комп'ютери";
declare and use where needed, not before

2021-04-16 05:25 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +                "The page title should match the condition");
Incorrect page title

2021-04-19 05:30 UTC, toleksyn approved these changes

2021-04-20 05:22 UTC, toleksyn requested changes

2021-04-20 05:22 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/LeftSidebar.java
> +    public CategoryPage openSalesCategory() {
too specific

2021-04-20 05:22 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        var chosenCategoryByCatalog = rozetkaHomePage
rename

2021-04-20 05:22 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +                .openCategoryPageByName(pageCategoryName.toLowerCase());
rename, fix

2021-04-20 05:22 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        var productWithDiscountPrice = productPage.getDiscountPrice();
rename both

2021-04-20 15:36 UTC, merged