Nromanchuk - rozetka test
toleksyn/ifa-120.ta pull request #119
Opened 2021-04-15 16:27 UTC by Vivanatalya

2021-04-16 05:20 UTC, toleksyn requested changes

2021-04-16 05:20 UTC, toleksyn commented on .gitignore
> +LeftSidebarCategories.java
??

2021-04-16 05:20 UTC, toleksyn requested changes

2021-04-16 05:20 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/LeftSidebarCategories.java
> +public enum LeftSidebarCategories {
this is unused

2021-04-19 05:30 UTC, toleksyn approved these changes

2021-04-20 05:19 UTC, toleksyn requested changes

2021-04-20 05:19 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +                .openHomePage();
fix

2021-04-20 05:19 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        var productPage = rozetkaHomePage
this is characteristicsPage

2021-04-21 05:23 UTC, toleksyn approved these changes

2021-04-21 19:27 UTC, SofiiaPro commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CategoryPage.java
> +    public int getCategoriesNumber() {
*count

2021-04-21 19:29 UTC, SofiiaPro commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CategoryPage.java
> +    public ProductsListPage openSubcategoriesAndProductsListPage(int index) {
number instead of index

2021-04-21 19:31 UTC, SofiiaPro commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductsListPage.java
> +        String filterNameCaps = filterName.toUpperCase().charAt(0)+filterName.substring(1,filterName.length());
change Caps

2021-04-21 19:33 UTC, SofiiaPro commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +                "product characteristic description should contains at least 1 row");
not row

2021-04-21 19:38 UTC, SofiiaPro commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        var questionsRowsAmount = productCharacteristicPage
questionsCount

2021-04-21 19:41 UTC, SofiiaPro commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        assertTrue(questionsRowsAmount > 0, "list size  should contain at least 1 text field");
rename

2021-04-21 19:41 UTC, SofiiaPro commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        var categoriesNumberOnPage = sportAndHobbiesCategoryPage.getCategoriesNumber();
count

2021-04-22 05:34 UTC, toleksyn requested changes

2021-04-22 05:34 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CategoryPage.java
> +        return $$x("//li[@class='portal-grid__cell']").size();
has no wait here, potentially unstable

2021-04-22 05:34 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CategoryPage.java
> +    public ProductsListPage openSubcategoriesAndProductsListPage(int number) {
rename, misleading

2021-04-22 05:34 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductsListPage.java
> +        String capitalizedFirstLetterFilterName = filterName
var

2021-04-22 05:34 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductsListPage.java
>      public ProductsListPage filterProductsList(String filterName) {
don't we have filtering already?

2021-04-22 05:34 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductsListPage.java
> +    public ProductsListPage searchInFilterMenu(String filterCategory, String filterName) {
rename

2021-04-22 05:34 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        var characteristicsListSize = productCharacteristicPage
characteristicAmount or *Count

2021-04-22 05:34 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        var categoriesCountOnPage = sportAndHobbiesCategoryPage.getCategoriesCount();
rename

2021-04-22 05:34 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +                .getProductListSize();
rename

2021-04-23 06:33 UTC, toleksyn requested changes

2021-04-23 06:33 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CategoryPage.java
> +                .shouldHave(CollectionCondition.sizeGreaterThanOrEqual(1)).size();
new line

2021-04-23 06:33 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CategoryPage.java
> +                .shouldHave(CollectionCondition.sizeGreaterThanOrEqual(1)).size();
static import

2021-04-23 06:33 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductPage.java
> +    public int getQuestionsAmount() {
rename

2021-04-23 06:33 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductsListPageWithSubcategories.java
> +}
??

2021-04-27 03:03 UTC, toleksyn requested changes

2021-04-27 03:03 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CategoryPage.java
> +    public ProductsListPageWithSubcategories openProductsListPageWithSubcategories(int number) {
step

2021-04-27 19:23 UTC, VladimirPetrat commented on src/test/java/com/softserveinc/ita/rozetka_test/ProductNavigationTest.java
>          assertTrue(middleProductPrice < lastProductPrice,
Fetch

2021-04-28 07:00 UTC, toleksyn requested changes

2021-04-28 07:00 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +                .openCategory("Спорт і захоплення");
fix

2021-04-29 07:10 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CategoryPage.java
empty file

2021-05-11 06:48 UTC, closed without merging