Rkhrabatyn - Added Order test
toleksyn/ifa-120.ta pull request #121
Opened 2021-04-15 18:35 UTC by romankhr

2021-04-16 05:19 UTC, toleksyn requested changes

2021-04-16 05:19 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/OrderPage.java
> +    public boolean isDisplayedConfirmOrderButton() {
isConfirmOrderButtonDisplayed()

2021-04-16 05:19 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/OrderTest.java
> +    public void putProductToBasketOpenOrder() {
why was this changed?

2021-04-16 05:19 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/OrderTest.java
> +                .isDisplayedConfirmOrderButton();
group these data into ShippingAddress class, add method setShippingAddress() to openOrderPage

2021-04-16 05:19 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/OrderTest.java
> +    public void insertBuyersCredentialsTest() {
rename

2021-04-18 06:07 UTC, VladimirPetrat commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/BasketPage.java
> +        var productPrice = ($x(format("(//*[@class='cart-product__price'])[%d]", numberOfProduct))
productPriceText?

2021-04-19 05:28 UTC, toleksyn requested changes

2021-04-19 05:28 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/OrderPage.java
> +                .replaceAll(" ", "");
new lines with two or more methods

2021-04-19 05:28 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/OrderTest.java
> +        var isDisplayedConfirmOrderButton = orderPage
rename

2021-04-19 19:06 UTC, romankhr commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/OrderPage.java
> +                .replaceAll(" ", "");
Fixed

2021-04-20 05:14 UTC, toleksyn requested changes

2021-04-20 05:14 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/OrderPage.java
> +        $x("//div[@class='form__row js-city']//li[1]").click();
you should have both setShippingAddress() and setSurname(), setName() etc methods and just those methods in setShippingAddress()

2021-04-21 05:22 UTC, toleksyn requested changes

2021-04-21 05:22 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/OrderTest.java
> +    public void testShippingAddressInsertion() {
rename

2021-04-21 05:22 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/OrderTest.java
> +                + shippingAddress.getSurname());
Incorrect ...
same for all

2021-04-22 05:31 UTC, toleksyn requested changes

2021-04-22 05:31 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/OrderPage.java
> +    public static String getCity() {
no static methods in PO

2021-04-22 05:31 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/OrderPage.java
> +    private OrderPage setCity(String city) {
these methods should be public

2021-04-22 12:16 UTC, merged