Sbendus - added showMoreProducts test
toleksyn/ifa-120.ta pull request #134
Opened 2021-04-20 19:36 UTC by SofiiaPro

2021-04-21 05:14 UTC, toleksyn requested changes

2021-04-21 05:14 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/HomePage.java
> +@Getter
better use specifically on field

2021-04-21 05:14 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        var chosenCategoryPageByCatalog = rozetkaHomePage
rename

2021-04-21 05:14 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        assertTrue(chosenCategoryPageByCatalog.getCategoryTitle().contains(categoryTitle),
split into var
newlines on 3 methods

2021-04-21 05:14 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +    public void testCompareProductPrices() {
rename, be specific

2021-04-21 05:14 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +                .openCategory("Знижки");
Знижки to var

2021-04-22 05:19 UTC, toleksyn requested changes

2021-04-22 05:19 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/Catalog.java
> +public class Catalog {
*Page

2021-04-22 05:19 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/Catalog.java
> +        SelenideElement category = $x(format("//ul[@class='menu-categories'] //a[contains(@class, 'menu-categories__link') and contains(text(), '%s')]", categoryName));
var

2021-04-22 05:19 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/Catalog.java
> +        SelenideElement category = $x(format("//ul[@class='menu-categories'] //a[contains(@class, 'menu-categories__link') and contains(text(), '%s')]", categoryName));
rename

2021-04-22 05:19 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/Header.java
> +    public Catalog openCatalog() {
rename

2021-04-22 05:19 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        var pageCategoryName = "Ноутбуки";
rename

2021-04-22 05:19 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        var chosenProductPage = rozetkaHomePage
??

2021-04-22 05:19 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        var catalogDropDownMenu = rozetkaHomePage
rename

2021-04-22 12:13 UTC, toleksyn requested changes

2021-04-22 12:13 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CatalogMenu.java
> +    public CategoryPage openCategory(String categoryName) {
openCategoryPage()

2021-04-22 12:13 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CatalogMenu.java
> +    public int getCategoryListSize() {
rename

2021-04-22 17:54 UTC, VladimirPetrat commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CatalogMenu.java
> +
Delete

2021-04-23 06:29 UTC, toleksyn requested changes

2021-04-23 06:29 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/CatalogMenu.java
> +    public int getCategoriesSize() {
rename

2021-04-23 06:29 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +    public void testSelectProductByLeftSidebar() {
rename

2021-04-23 06:29 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +    public void testSelectProductByLeftSidebar() {
rename

2021-04-23 06:29 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        var isLaptopCategoryPageCorrect = laptopCategoryPage
*Opened()

2021-04-23 06:29 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +                .openCategoryPageByName(categoryName.toLowerCase());
no new line
rename

2021-04-23 06:29 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        assertTrue(!lastProductName.equals(extendedLastProductName),
assertFalse

2021-04-27 02:51 UTC, toleksyn requested changes

2021-04-27 02:51 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductPage.java
> +        return new CheaperTogetherMenu();
there's no open action here, rename

2021-04-27 02:51 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +                .openCategory(categoryName);
no new line

2021-04-27 19:09 UTC, VladimirPetrat commented on src/main/java/com/softserveinc/ita/rozetka/components/CheaperTogetherMenu.java
> +                .text();
No need to new line

2021-04-27 19:10 UTC, VladimirPetrat commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductsListPage.java
>      public AgeConfirmationPopup getAgeConfirmationPopup() {
Make fetch

2021-04-27 19:11 UTC, VladimirPetrat commented on src/test/java/com/softserveinc/ita/rozetka_test/ProductNavigationTest.java
>          assertTrue(middleProductPrice < lastProductPrice,
Fetch

2021-04-27 19:13 UTC, VladimirPetrat commented on src/test/java/com/softserveinc/ita/rozetka_test/ProductNavigationTest.java
> +        var catalogMenu = header.openCatalogMenu();
Test situated in worng class

2021-04-29 02:03 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +        var laptopCategoryPageByLink = laptopProductPage.openCategoryPageByLink(categoryName.toLowerCase());
rename

2021-04-29 02:03 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +        assertTrue(isLaptopCategoryPageOpened, "Incorrect page title");
fix

2021-04-29 02:03 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +        assertTrue(isProductListPageOpened, "Incorrect page title");
fix

2021-04-29 02:03 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +        assertTrue(isProductListPageOpened, "Incorrect page title");
this is not enought

2021-04-29 02:04 UTC, toleksyn requested changes

2021-04-29 02:04 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +        var subcategoryAmount = makeUpCategory.getCategoriesAmount();
fix

2021-04-29 07:21 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +        var laptopCategoryPageByLink = laptopProductPage.openCategoryPageByLink(categoryName.toLowerCase());
not sure

2021-05-11 06:56 UTC, closed without merging