CommonBracnh - Added allure steps, created new test class
toleksyn/ifa-120.ta pull request #148
Opened 2021-04-22 17:49 UTC by VladimirPetrat

2021-04-23 06:17 UTC, toleksyn requested changes

2021-04-23 06:17 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaCategoryNavigationTests.java
> +    private LeftSidebar rozetkaLeftSidebar;
drop rozetka in names

2021-04-23 06:17 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +    private Header rozetkaHeader;
same

2021-04-26 10:02 UTC, SerhiiHladkyi commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/HomePage.java
> +                .shouldHave(CollectionCondition.sizeGreaterThanOrEqual(1))
fix

2021-04-27 02:48 UTC, toleksyn requested changes

2021-04-27 02:48 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/utility_class/ShippingAddress.java
> +package com.softserveinc.ita.rozetka.utility_class;
rename

2021-04-27 02:48 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +        catalogMenu = new HomePage().openHomePage().getCatalogMenu();
new lines

2021-04-27 07:22 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/utility_class/ShippingAddress.java
> +package com.softserveinc.ita.rozetka.utility_class;
models

2021-04-27 09:54 UTC, merged