Ikuguk - add test main sections presence
toleksyn/ifa-120.ta pull request #149
Opened 2021-04-22 21:22 UTC by kuguk

2021-04-23 06:15 UTC, toleksyn requested changes

2021-04-23 06:15 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/HomePage.java
> +    public int getProductsCountOnPage(int countNotLess) {
getProductCount(), no param

2021-04-23 06:15 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/HomePage.java
> +    public int getProductsCountOnPage(int countNotLess) {
getRecentlyViewedProductsSection().getProductsCount()

2021-04-23 06:15 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        randomProductNumber = randomProductNumber > 1 ? randomProductNumber : 1;
add 1 on line 145

2021-04-23 06:15 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        List<String> productSectionsTitles = productPage.getProductSectionsTitleList(3);
var

2021-04-23 06:15 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        assertTrue(productSectionsTitles.contains("Опис" + " " + productTitle),
format()

2021-04-25 13:47 UTC, kuguk commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        randomProductNumber = randomProductNumber > 1 ? randomProductNumber : 1;
fixed using Math.max()

2021-04-25 13:47 UTC, kuguk commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        List<String> productSectionsTitles = productPage.getProductSectionsTitleList(3);
fixed

2021-04-25 13:47 UTC, kuguk commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        assertTrue(productSectionsTitles.contains("Опис" + " " + productTitle),
fixed

2021-04-25 19:13 UTC, kuguk commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/HomePage.java
> +    public int getProductsCountOnPage(int countNotLess) {
fixed

2021-04-27 02:46 UTC, toleksyn requested changes

2021-04-27 02:46 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/DeliveryCityPage.java
> +public class DeliveryCityPage {
add steps to page object methods

2021-04-27 02:46 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/HomePage.java
> +    public ProductPage openProductByNumberInSection(int number, String sectionName) {
use PO and OOP

2021-04-27 02:46 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        assertTrue(isSubmitButtonDisplayed, "Opened page is not functional");
fix

2021-04-27 07:18 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/HomePage.java
> +    public ProductPage openProductByNumberInSection(int number, String sectionName) {
getSection().openProductByNumber()

2021-04-27 17:15 UTC, kuguk commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/HomePage.java
> +    public ProductPage openProductByNumberInSection(int number, String sectionName) {
fixed

2021-04-27 17:21 UTC, kuguk commented on src/test/java/com/softserveinc/ita/rozetka_test/RozetkaProductNavigationTest.java
> +        assertTrue(isSubmitButtonDisplayed, "Opened page is not functional");
fixed

2021-04-27 18:25 UTC, kuguk commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/DeliveryCityPage.java
> +public class DeliveryCityPage {
fixed

2021-04-27 18:28 UTC, VladimirPetrat commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/HomePage.java
> +                .click();
No need to new line

2021-04-27 18:31 UTC, VladimirPetrat commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductsSectionPage.java
> +public class ProductsSectionPage {
Its only part of page

2021-04-27 18:35 UTC, VladimirPetrat commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductTrackingPage.java
> +    public HamburgerBar openHamburgerBar() {
Same method present in header

2021-04-27 18:38 UTC, VladimirPetrat commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductsSectionPage.java
> +                .text();
Same

2021-04-27 20:15 UTC, kuguk commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/HomePage.java
> +                .click();
fixed

2021-04-27 20:21 UTC, kuguk commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductsSectionPage.java
> +public class ProductsSectionPage {
renamed to ProductsSection

2021-04-27 20:22 UTC, kuguk commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductsSectionPage.java
> +                .text();
fixed

2021-04-27 20:38 UTC, kuguk commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductTrackingPage.java
> +    public HamburgerBar openHamburgerBar() {
will be optimized

2021-04-28 06:55 UTC, toleksyn requested changes

2021-04-28 06:55 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/Footer.java
> +    public ProductTrackingPage openTrackingPage() {
rename

2021-04-28 06:55 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/Footer.java
> +        $x("//a[contains(text(),'Відстежити замовлення')]").click();
re-do

2021-04-28 06:55 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/ProductsSection.java
> +    public int getProductsCount(String sectionName) {
init section name in constructor

2021-04-28 06:55 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/HomePage.java
> +    public ProductsSection getProductsSectionByName(String sectionName) {
rename

2021-04-28 06:55 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductTrackingPage.java
> +        var errorMessage = "";
declare where used

2021-04-28 06:55 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductTrackingPage.java
> +            blankCredentialsAllowed = false;
code convention

2021-04-28 06:55 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductTrackingPage.java
> +        if (errorMessage.equals("Введено невірну адресу ел. пошти або номер телефону"))
just return expression

2021-04-28 06:55 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/FooterTest.java
> +    private Footer footerBar;
rename

2021-04-28 06:55 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/FooterTest.java
> +        assertEquals(pageTitle, "ROZETKA — Мої замовлення | Особистий кабінет");
assert messages ??

2021-04-28 06:55 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/ProductNavigationTest.java
> +        assertTrue(productSectionsTitles.contains(format("Відгуки покупців %s", ProductReviewCount)) ||
no joined asserts

2021-04-28 07:20 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/ProductNavigationTest.java
> +        assertTrue(productSectionsTitles.contains(format("Відгуки покупців %s", ProductReviewCount)) ||
if(product count == 0) {
message
} else {another message}

2021-04-29 02:00 UTC, toleksyn requested changes

2021-04-29 02:00 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/HamburgerBar.java
> +        return $x("//*[contains(@class, 'side-menu__auth')]").toString();
text()

2021-04-29 02:00 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/ProductsSection.java
> +    int randomNumber;
??

2021-04-29 02:00 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/ProductsSection.java
> +    }
can use @AllArgsConstructor instead

2021-04-29 02:00 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/ProductsSection.java
> +    public int randomProductNumber() {
this is not a PO method, only actions and data return

2021-04-29 02:00 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/ProductsSection.java
> +    public ProductPage openRandomProduct() {
openProductAtPosition(randonmPos)

2021-04-29 02:00 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/BasketPage.java
> +import java.util.Objects;
??

2021-04-29 02:00 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/HomePage.java
> +    @Step("Home page: open product by number for number {number}")
fix

2021-04-29 02:00 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductPage.java
> +        String reviewSectionText = ($x("//*[contains(@class,'product-comm')]//span[contains(@class,'product-t')]").text());
var

2021-04-29 02:00 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductPage.java
> +        String reviewSectionText = ($x("//*[contains(@class,'product-comm')]//span[contains(@class,'product-t')]").text());
not text, name

2021-04-29 02:00 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductPage.java
> +        return true;
instead just return reviewSectionText.replaceAll("[0-9]", "").equals("")) && reviewSectionText.contains("Додати відгук до товару"

2021-04-29 02:00 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductTrackingPage.java
> +    @Step("ProductTrackingPage: checking permission for Blank Credentials")
remove step

2021-04-29 02:00 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductTrackingPage.java
> +        return (!errorMessage.equals("Введено невірну адресу ел. пошти або номер телефону"));
remove brackets

2021-04-29 02:00 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/FooterTest.java
> +    public void testBanningOrderTrackingWithoutLogin() {
rename

2021-04-29 02:00 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/ProductNavigationTest.java
> +                .openProductsSection("Гарячі новинки");
create enum for section name
enum ProductSection {
    HOT_NEW_PRODUCTS("Гарячі новинки")
}

2021-04-29 07:18 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductTrackingPage.java
> +        $x("//button[contains(@class, 'button button--large')]").click();
hidden action
.submit()
.save()

2021-04-29 07:19 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/FooterTest.java
> +    public void testBanningOrderTrackingWithoutLogin() {
testProductCannotBeTrackedWhenNotLoggedIn

2021-05-02 20:18 UTC, VladimirPetrat commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/HomePage.java
> +        IntStream.range(0, 18).forEach(i -> actions()     // page scrolling to dynamically increase the count of products sections
"i" is not representative name of iterator.

2021-05-02 20:19 UTC, VladimirPetrat commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductPage.java
> +                .sendKeys(Keys.PAGE_DOWN)
same

2021-05-06 07:35 UTC, toleksyn requested changes

2021-05-06 07:35 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductPage.java
> +        return (reviewSectionName.contains("Відгуки покупців")) || reviewSectionName.contains("Додати відгук до товару");
re-do

2021-05-06 07:35 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductTrackingPage.java
> +    public ProductTrackingPage loginWithBlankCredentials() {
rename, login()

2021-05-06 07:35 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/FooterTest.java
> +        openFooter();
PO, deliveryHelpPage.getFooter()

2021-05-07 07:07 UTC, toleksyn requested changes

2021-05-07 07:07 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/ProductsSection.java
> +    public int getProductsCountInSection() {
rename

2021-05-07 07:07 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/ValuationCalc.java
> +public class ValuationCalc {
?

2021-05-07 07:07 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/enums/ProductSections.java
> +public enum ProductSections {
*Section

2021-05-07 07:07 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/enums/YesNoAnswer.java
> +    private final String yesNoAnswer;
rename

2021-05-07 07:07 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/DeviceExchangePage.java
> +    public ValuationCalc openValuationCalc() {
rename

2021-05-07 07:07 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/DeviceExchangePage.java
> +    public Footer getFooter() {
rename

2021-05-07 07:38 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/ValuationCalc.java
> +public class ValuationCalc {
*Section

2021-05-07 07:44 UTC, toleksyn requested changes

2021-05-07 07:44 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/ValuationCalc.java
> +    public void setDevice(String deviceType, String brandName, String deviceName) {
step

2021-05-07 07:44 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/ValuationCalc.java
> +    }
switch back to default context

2021-05-07 07:44 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/enums/DeviceSurfaceState.java
> +    private final String surfaceState;
rename

2021-05-07 07:44 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/enums/DeviceSurfaceState.java
> +    private final String surfaceState;
partialLocator

2021-05-07 07:44 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ContactsPage.java
> +    public Footer getFooter() {
rename

2021-05-07 07:44 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/DeviceExchangePage.java
> +    public ValuationCalc openValuationCalc() {
scrollToValueCalculator()

2021-05-07 07:44 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/FooterTest.java
> +        valuationCalc.setScreenState(screenState);
setScreenState(ENUM)

2021-05-11 06:55 UTC, toleksyn requested changes

2021-05-11 06:55 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/ValueCalculatorSection.java
> +    }
all set*() methods should return this

2021-05-11 06:55 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/DeviceExchangePage.java
> +    public ValueCalculatorSection scrollToValueCalculator() {
rename *Section()

2021-05-11 06:55 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/DeviceExchangePage.java
> +        return new DeviceExchangePage();
no need for separate method

2021-05-11 06:55 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ProductTrackingPage.java
> +    public boolean isBlankCredentialsAllowed() {
are*()

2021-05-17 06:27 UTC, merged