Shladkyi - add comparison test
toleksyn/ifa-120.ta pull request #160
Opened 2021-05-05 10:28 UTC by SerhiiHladkyi

2021-05-06 07:10 UTC, toleksyn requested changes

2021-05-06 07:10 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/ComparisonPopup.java
> +    public ComparisonPage openComparisonPageByNumber(int number) {
openComparisonPageFromList ?

2021-05-06 07:10 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/Header.java
> +        $x("//rz-comparison//button[@class='header__button ng-star-inserted']").click();
re-do

2021-05-06 07:10 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ComparisonPage.java
> +    public ComparisonPage openDifferentCharacteristics() {
showDifferences()

2021-05-06 07:10 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/ComparisonTest.java
> +                        .add(allCharacteristics.get(index)));
comparisonPage.getCharacteristicForProduct(1)

2021-05-07 07:32 UTC, toleksyn requested changes

2021-05-07 07:32 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ComparisonPage.java
> +                throw new IllegalArgumentException();
re-do

2021-05-07 07:32 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/ComparisonTest.java
> +        var isAllCharacteristicsDifferent = range(0, differentFirstProductCharacteristics.size())
are*

2021-05-07 08:57 UTC, SerhiiHladkyi commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ComparisonPage.java
> +                throw new IllegalArgumentException();
fix

2021-05-11 06:57 UTC, toleksyn requested changes

2021-05-11 06:57 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ComparisonPage.java
> +                        .collect(toCollection(ArrayList::new));
duplication, re-do

2021-05-11 06:57 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ComparisonPage.java
> +                throw new IllegalArgumentException();
no empty exceptions

2021-05-13 07:09 UTC, toleksyn requested changes

2021-05-13 07:09 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ComparisonPage.java
> +        } throw new IllegalArgumentException("Incorrect number of product");
brackets

2021-05-13 07:09 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/page_objects/ComparisonPage.java
> +                    .collect(toCollection(ArrayList::new));
collect(toList())

2021-05-17 06:30 UTC, merged