Ikuguk-added-new-test
toleksyn/ifa-120.ta pull request #162
Opened 2021-05-13 21:48 UTC by kuguk

2021-05-17 06:36 UTC, toleksyn requested changes

2021-05-17 06:36 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/CatalogMenu.java
> +    public ProductsListPage openProductsListByCategoryInCatalogMenu(String hoveredCategoryName, String... subCategoryName) {
avoid varargs

2021-05-17 06:36 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/CatalogMenu.java
> +    public ProductsListPage openProductsListByCategoryInCatalogMenu(String hoveredCategoryName, String... subCategoryName) {
rename

2021-05-17 06:36 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +        SoftAssert softassert = new SoftAssert();
var

2021-05-17 06:36 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +        for (var productNumber = 1; productNumber <= productsCount; ) {//productNumber = productNumber + productCount / 2) {
?

2021-05-17 06:36 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +                productNumber = productNumber + productsCount / 2;
java code convention

2021-05-17 18:12 UTC, kuguk commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +        for (var productNumber = 1; productNumber <= productsCount; ) {//productNumber = productNumber + productCount / 2) {
fixed

2021-05-17 18:12 UTC, kuguk commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +                productNumber = productNumber + productsCount / 2;
fixed

2021-05-17 18:14 UTC, kuguk commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +        SoftAssert softassert = new SoftAssert();
fixed

2021-05-17 18:14 UTC, kuguk commented on src/main/java/com/softserveinc/ita/rozetka/components/CatalogMenu.java
> +    public ProductsListPage openProductsListByCategoryInCatalogMenu(String hoveredCategoryName, String... subCategoryName) {
fixed

2021-05-19 05:49 UTC, toleksyn requested changes

2021-05-19 05:49 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +            }
this logic is not obvious

2021-05-19 07:46 UTC, kuguk commented on src/test/java/com/softserveinc/ita/rozetka_test/CategoryNavigationTests.java
> +            }
fixed

2021-05-24 06:03 UTC, merged