V petrat branch
toleksyn/ifa-120.ta pull request #6
Opened 2021-03-23 13:41 UTC by VladimirPetrat

Added multiple browser support. Errors in names of fields and methods are fixed.

2021-03-24 07:03 UTC, toleksyn requested changes

2021-03-24 07:03 UTC, toleksyn commented on pom.xml
> +            <artifactId>selenium-support</artifactId>
why is this needed?

2021-03-24 07:03 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/vPetrat/pageObjects/GoogleHomePage.java
> +    public GoogleSearchResultPage searchForTheSpecifiedRequest(String request) {
rename

2021-03-24 07:03 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/vPetrat/pageObjects/GoogleHomePage.java
> +        WebElement searchInputElement = TestRunner.getDriver().findElement(searchInput);
duplication

2021-03-24 07:03 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/vPetrat/resources/DriverType.java
> +public enum DriverType {
wasn't part of task, didn't review

2021-03-24 07:03 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/vPetrat/resources/googleSearchRequest.properties
> +searchRequestKey=Funny Kitties
overcomplication

2021-03-24 09:20 UTC, VladimirPetrat commented
Comment taken into Account. Test multiple result links added.

2021-03-25 06:57 UTC, toleksyn requested changes

2021-03-25 06:57 UTC, toleksyn commented on pom.xml
> +            <version>${selenium.java.version}</version>
do not change variables here, change to needed version in chrome.driver.version

2021-03-25 07:44 UTC, toleksyn requested changes

2021-03-25 07:44 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/pageobjects_task/GoogleSearchTest.java
> +package com.softserveinc.ita.pageobjects_task;
create your package - vpetrat - and move test there

2021-03-25 07:44 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/vPetrat/pageObjects/GoogleHomePage.java
> +package com.softserveinc.ita.vPetrat.pageObjects;
code convention, rename - vpetrat, pageobjects
package names are all lower case with underscores if needed

2021-03-25 08:37 UTC, merged